### ISSUE TITLE
Python Module Error

### ISSUE THREAD

**Issue by SyrozXO** [hitsomeshots/fuckingfast-link-generator#1]
There is a error where it says modulenotfounderror no module named aiohttp

**Comment by SyrozXO** [comment]
ok. figured out how to download aiohttp and bm4 but now im completely stuck
![image_2024-07-23_064141416](https://github.com/user-attachments/assets/4552047d-33cd-4634-827e-34ac47267e03)

**Comment by hitsomeshots** [comment]
check the other repo should work
